### ISSUE TITLE
Error while getting fixture with anonymous references

### ISSUE THREAD

**Issue by jvrsantacruz** [uber/charlatan#47]
Error resolving anonymous references based on list of objects:

```
(...)
charlatan/utils.pyc in richgetter(obj, path)
    174             obj = getattr(obj, name)
    175             continue
--> 176         obj = obj[name]
    177 
    178     return obj

TypeError: list indices must be integers, not str
```

This happens loading the fixture

```
>>> import charlatan
>>> fm = charlatan.FixturesManager(session)
>>> fm.load('fixtures.yaml', 'app.models')

# Specific index is OK
>>> fm.get_fixture('department.0')
Department

# Whole collection raises error
>>> fm.get_fixture('departments')
(...)
TypeError: list indices must be integers, not str
```
```
office:
  model: Office

offices:
  inherit_from: office
  objects:
    -
       name: 'Office0'

    -
       name: 'Office1'

department:
  model: Department

departments:
  inherit_from: department
  objects:
    -
       name: 'Department0'
       office: !rel offices.0

    -
       name: 'Department1'
       office: !rel offices.1
```
It works using keys 0, 1 for offices instead of a list, but it changes the `get_fixture` return type from `list` to `dict`.
