### ISSUE TITLE
Nested custom constructors are not evaluated

### ISSUE THREAD

**Issue by kooba** [uber/charlatan#56]
This could be a problem with pyyaml itself. 

When creating fixtures without models and nesting `!now` only first level is evaluated

This yaml definition:

```yaml
simple_dict:
  fields:
    created_at: !now
    nested:
      created_at: !now
```
produces this output:

```python
{ 
    'created_at': datetime.datetime(2015, 11, 25, 17, 27, 3, 119923, tzinfo=<UTC>), 
    'nested': {
        'created_at': <function configure_yaml.<locals>.now_constructor.<locals>.get_now at 0x1052cbbf8>
    }
}
```

Cheers,
Jakub
